#!/bin/bash

set -o nounset
set -o noclobber

typeset -r MYSELF="$(readlink -f $0)"
typeset -r MYPATH="${MYSELF%/*}"
typeset -r MYCALL="$0"

# Load the lib. Will define variables to be used in this script:
# Example: this script is in /home/myuser/services/scripts/myapp-db
# APP_NAME = myapp-db
# APP_PACK = myapp
# APP_BASE = /home/myuser/services/apps/myapp
# DAT_BASE = /home/myuser/services/data/myapp/myapp-db
# SRC_BASE = /home/myuser/services/srcs/myapp/myapp-db
# TMP_BASE = /home/myuser/services/temp/myapp/myapp-db
# ## Constructed from $TMP_BASE and $DAT_BASE
# TMP_PIDS = /home/myuser/services/temp/myapp/myapp-db/pids
# LOG_BASE = /home/myuser/services/data/myapp/myapp-db/logs

# You can specify the app version to be used by changing RUN_VERS.
# By default, RUN_VERS="current", and you need to define it before loading the lib
# RUN_VERS = current
# RUN_BASE = "$APP_BASE/${APP_NAME}-${RUN_VERS}
#          = /home/myuser/services/apps/myapp/myapp-db-current
. $MYPATH/amsvc.lib

# Now, you can use some variables and leverage 'amsvc_main "$@"'
# The following "RUN_" vars are used by amsvc_start/stop/status

RUN_BIN="$RUN_BASE/usr/bin/influxd"
RUN_CFG="$CFG_BASE/amsvc.conf"
#RUN_OPTCFG="-config"
RUN_OPTPID="-pidfile"
RUN_OPTSTART="run -config $RUN_CFG"
#RUN_OPTSTOP=""
#RUN_USER="myuser"
RUN_DAEMON="1"

function upgrade_getlatest {
	typeset out="$(fetch_http "https://portal.influxdata.com/downloads" "-")"
	typeset vers="$(echo "$out" | grep -oP influxdb/releases/influxdb-.+?_linux_amd64.tar.gz | head -n 1)"
	vers="${vers%%_linux_amd64.tar.gz}"
	vers="${vers##*/influxdb-}"

	echo "$vers"
}

function upgrade_prepare {
	typeset vers="$1"

	typeset url="https://dl.influxdata.com/influxdb/releases/influxdb-${vers}_linux_amd64.tar.gz"
	app_deploy "$vers" "$url" "usr/bin/influxd"
}

function upgrade_confgen {
	[[ -e "$RUN_CFG" ]] && {
		log_inf "Configuration file '$RUN_CFG' already exists. Skipping"
		return 0
	}

	# Generate default file
	cat <<-EOT >> "$RUN_CFG"
	[meta]
	  dir = "$DAT_BASE/meta"

	[data]
	  # Stores the TSM files
	  dir = "$DAT_BASE/data"
	  # Stores the WAL files
	  wal-dir = "$DAT_BASE/wal"
	EOT
}

function upgrade_confdiff {
	typeset versnew="$1"
	typeset versold="$2"

	typeset pathold="$(app_getpath "$versold")"
	typeset pathnew="$(app_getpath "$versnew")"

	[[ -d "$pathold" ]] || {
		log_inf "Old version is not present. Skipping"
		return 0
	}

	# Fetch the config with old config
	typeset confold="$($pathold/usr/bin/influxd config -config $RUN_CFG)"
	typeset confnew="$($pathnew/usr/bin/influxd config -config $RUN_CFG)"

	file_diff <(echo "$confold") <(echo "$confnew")
}
# upgrade_confmerge "$VERSION1" "$VERSION2"
# upgrade_test "$VERSION"


# Call our lib main function
amsvc_main "$@"
